import { StyleSheet, Platform } from 'react-native'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  title: {
    fontSize: 42,
    fontWeight: '700',
    color: '#5809C0',
    textAlign: 'center',
    marginBottom: 30,
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  errorContainer: {
    backgroundColor: '#FFE5E5',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
  },
  errorText: {
    color: '#D32F2F',
    fontSize: 14,
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  authContainer: {
    backgroundColor: '#F9F9F9',
    padding: 32,
    borderRadius: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    alignItems: 'center',
  },
  authTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#5809C0',
    marginBottom: 12,
    fontFamily: Platform.OS === 'web' ? 'Oswald, sans-serif' : undefined,
  },
  authDescription: {
    fontSize: 14,
    color: '#5809C0',
    textAlign: 'center',
    marginBottom: 16,
    opacity: 0.8,
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  redirectUriContainer: {
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    width: '100%',
  },
  redirectUriLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#5809C0',
    marginBottom: 8,
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  redirectUriText: {
    fontSize: 11,
    color: '#5809C0',
    fontFamily: Platform.OS === 'web' ? 'monospace' : undefined,
    wordBreak: 'break-all',
    marginBottom: 8,
  },
  redirectUriNote: {
    fontSize: 10,
    color: '#5809C0',
    opacity: 0.6,
    fontStyle: 'italic',
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  loginButton: {
    backgroundColor: '#1DB954',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
    minWidth: 200,
  },
  loginButtonDisabled: {
    opacity: 0.6,
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  controls: {
    marginBottom: 24,
  },
  loadButton: {
    backgroundColor: '#5809C0',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
  },
  loadButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  filters: {
    backgroundColor: '#F9F9F9',
    padding: 20,
    borderRadius: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  filterTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#5809C0',
    marginBottom: 16,
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  filterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 12,
  },
  filterInput: {
    flex: 1,
  },
  filterLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#5809C0',
    marginBottom: 8,
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  input: {
    borderWidth: 2,
    borderColor: '#EFEFEF',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#5809C0',
    backgroundColor: '#FFFFFF',
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  clearButton: {
    backgroundColor: '#D3C2F7',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  clearButtonText: {
    color: '#5809C0',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  tracksContainer: {
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#5809C0',
    marginBottom: 16,
    fontFamily: Platform.OS === 'web' ? 'Oswald, sans-serif' : undefined,
  },
  infoText: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    padding: 20,
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  trackCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 8px rgba(88, 9, 192, 0.1)',
    } : {
      shadowColor: '#5809C0',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    }),
  },
  trackHeader: {
    marginBottom: 12,
  },
  trackInfo: {
    flex: 1,
  },
  trackName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#5809C0',
    marginBottom: 4,
    fontFamily: Platform.OS === 'web' ? 'Oswald, sans-serif' : undefined,
  },
  trackArtist: {
    fontSize: 16,
    color: '#5809C0',
    opacity: 0.8,
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  trackDetails: {
    marginTop: 8,
  },
  detailRow: {
    flexDirection: 'row',
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#5809C0',
    marginRight: 8,
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  detailValue: {
    fontSize: 14,
    color: '#5809C0',
    flex: 1,
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
  loadingText: {
    fontSize: 12,
    color: '#999',
    fontStyle: 'italic',
    fontFamily: Platform.OS === 'web' ? 'Figtree, sans-serif' : undefined,
  },
})

export default styles

